WebProject/Controllers/FuelController.cs
using DataAccessLayer;
using DataLayer.PersistanceLayer;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebProject.App_Start;
using WebProject.Helpers;

namespace WebProject.Controllers
{
    public class FuelController : Controller
    {
        public IDataAccessLayer _dataAccessLayer = new DataAccessLayer.DataAccessLayer();
        public ErrorHelper _errorHelper = new ErrorHelper();
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Fuel
        [Authorization]
        public ActionResult Index()
        {
            ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
            ViewBag.TrucksForDropDown = _dataAccessLayer.GetTrucksForDropDown();
            return View();
        }
        [Authorization]
        public ActionResult EditFuel()
        {
            ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
            ViewBag.TrucksForDropDown = _dataAccessLayer.GetTrucksForDropDown();
            return View();
        }
        [Authorization]
        public ActionResult GetFuelInfo()
        {
            try
            {
                var fuelData = _dataAccessLayer.GetFuelInfo();
                var grouping = fuelData.GroupBy(x=>x.WorkerName).Select(g => new { Worker = g.Key, RealConsumptionAvg = g.ToList().Average(x=>x.RealConsumption),KM = (g.LastOrDefault().FueledKM - g.FirstOrDefault().FueledKM), TotalDisel = g.Sum(x => x.DieselValue), TotalAdBlue = g.Sum(x=>x.AdblueValue) , FuelData = g.ToList() }).ToList();

                return Json(new { fuelData = grouping });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetFuelInfo \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult SaveFuel(Fuel fuel)
        {
            try
            {
                var fuelId = _dataAccessLayer.SaveFuel(fuel);

                return Json(new { fuelId });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in SaveFuel with id {0} \n\r : {1} - {2}",fuel.Id, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetFuelByid(Guid fuelId)
        {
            try
            {
                return Json(new { fuel = _dataAccessLayer.GetFuelById(fuelId), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetFuelByid for fueld with id {0} \n\r : {1} - {2}",fuelId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult DeleteFuel(Guid fuelId)
        {
            try
            {
                _dataAccessLayer.DeleteFuel(fuelId);

                return Json(new { success = "true" });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in DeleteFuel for fueld with id {0} \n\r : {1} - {2}", fuelId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetEstimatedConsumtionSumForDriverAndDate(Guid workerId, DateTime date)
        {
            try
            {
                return Json(new { totalEstimatedConsumtion = _dataAccessLayer.GetEstimatedConsumtionSumForDriverAndDate(workerId,date) });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetEstimatedConsumtionSumForDriverAndDate \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult ExportFuelDataForTruckByDateInterval(Guid truckId, DateTime startDate, DateTime endDate)
        {
            try
            {
                log.Info(string.Format("Utilizatorul {0} a descarcat un excel cu alimentari pentru masina {1} in intervalul orar {2} - {3}.", Session["Username"], truckId, startDate, endDate));

                var truck = _dataAccessLayer.GetTruck(truckId);
                var fileName = string.Format("Alimentari-{0}.xls", truck.RegistrationNumber);

                var fuelData = _dataAccessLayer.GetFuelInfo();
                var gv = AdaptGridViewForExport(fuelData.Where(x => x.Date <= endDate && x.Date >= startDate && x.Truck == truckId).ToList());

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename=" + fileName);
                Response.ContentType = "application/ms-excel";
                Response.Charset = "";
                StringWriter objStringWriter = new StringWriter();
                HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                gv.RenderControl(objHtmlTextWriter);
                Response.Output.Write(objStringWriter.ToString());
                Response.Flush();
                Response.End();

                ViewBag.TrucksForDropDown = _dataAccessLayer.GetTrucksForDropDown();
                ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
                return View("Index");
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in FuelController - ExportFuelDataForWorkerByDateInterval \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new
                {
                    error = _errorHelper.GetErrorMessage(ex)
                });
            }
        }
        [Authorization]
        public ActionResult ExportFuelDataForWorkerByDateInterval(Guid workerId, DateTime startDate, DateTime endDate)
        {
            try
            {
                log.Info(string.Format("Utilizatorul {0} a descarcat un excel cu alimentari pentru soferul {1} in intervalul orar {2} - {3}.", Session["Username"], workerId, startDate, endDate));

                var worker = _dataAccessLayer.GetWorker(workerId);
                var fileName = string.Format("Alimentari-{0}.xls", worker.WorkerName);

                var fuelData = _dataAccessLayer.GetFuelInfo();
                var gv = AdaptGridViewForExport(fuelData.Where(x => x.Date <= endDate && x.Date >= startDate && x.Worker == workerId).ToList());

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename="+ fileName);
                Response.ContentType = "application/ms-excel";
                Response.Charset = "";
                StringWriter objStringWriter = new StringWriter();
                HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                gv.RenderControl(objHtmlTextWriter);
                Response.Output.Write(objStringWriter.ToString());
                Response.Flush();
                Response.End();

                ViewBag.TrucksForDropDown = _dataAccessLayer.GetTrucksForDropDown();
                ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
                return View("Index");
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in FuelController - ExportFuelDataForWorkerByDateInterval \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new
                {
                    error = _errorHelper.GetErrorMessage(ex)
                });
            }
        }

        private GridView AdaptGridViewForExport(List<Fuel> drivesToBeExported)
        {
            var gv = new GridView();
            gv.DataSource = drivesToBeExported;
            gv.DataBind();
            if (drivesToBeExported.Any())
            {
                gv.HeaderRow.Cells[0].Visible = false;
                gv.HeaderRow.Cells[1].Visible = false;
                gv.HeaderRow.Cells[2].Visible = false;
                gv.HeaderRow.Cells[3].Visible = false;
                gv.HeaderRow.Cells[4].Visible = false;
                gv.HeaderRow.Cells[7].Visible = false;
                gv.HeaderRow.Cells[9].Visible = false;
                gv.HeaderRow.Cells[11].Visible = false;
                gv.HeaderRow.Cells[13].Visible = false;
                gv.HeaderRow.Cells[15].Visible = false;
                gv.HeaderRow.Cells[17].Visible = false;
                gv.HeaderRow.Cells[19].Visible = false;
                gv.HeaderRow.Cells[21].Visible = false;
                gv.HeaderRow.Cells[23].Visible = false;
                gv.HeaderRow.Cells[25].Visible = false;
                gv.HeaderRow.Cells[26].Visible = false;
                gv.HeaderRow.Cells[29].Visible = false;

                gv.HeaderRow.Cells[5].Text = Resources.Labels.NumeSofer;
                gv.HeaderRow.Cells[6].Text = Resources.Labels.ConsumGPSInitial;
                gv.HeaderRow.Cells[8].Text = Resources.Labels.ConsumGPSFinal;
                gv.HeaderRow.Cells[10].Text = Resources.Labels.ConsumGPS;

WebProject/Controllers/TruckController.cs
using DataAccessLayer;
using DataLayer.PersistanceLayer;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using WebProject.App_Start;
using WebProject.Helpers;

namespace WebProject.Controllers
{
    public class TruckController : Controller
    {
        public IDataAccessLayer _dataAccessLayer = new DataAccessLayer.DataAccessLayer();
        public ErrorHelper _errorHelper = new ErrorHelper();
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Truck
        [Authorization]
        public ActionResult Index()
        {
            return View();
        }
        [Authorization]
        public ActionResult EditTruck()
        {
            ViewBag.BrandsForDropDown = _dataAccessLayer.GetBrands();
            return View();
        }
        [Authorization]
        public ActionResult GetTrucks()
        {
            try
            {
                return Json(new { trucks = _dataAccessLayer.GetTrucks(), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetTrucks \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult SaveTruck(Truck truck)
        {
            try
            {
                var truckId = _dataAccessLayer.SaveTruck(truck);
                var notifications = _dataAccessLayer.GetNotifications();
                Session["NotificationNumber"] = notifications.Any() ? notifications.Count : 0;
                Session["Notifications"] = notifications.Any() ? notifications : new List<Notification>();

                return Json(new { truckId });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in SaveTruck for truckId: {0} \n\r : {1} - {2}",truck.Id, ex.Message,ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetTruck(Guid idTruck)
        {
            try
            {
                return Json(new { truck = _dataAccessLayer.GetTruck(idTruck), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetTruck for truckId: {0} \n\r : {1} - {2}", idTruck, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult DeleteTruck(Guid truckId)
        {
            try
            {
                _dataAccessLayer.DeleteTruck(truckId);

                var notifications = _dataAccessLayer.GetNotifications();
                Session["NotificationNumber"] = notifications.Any() ? notifications.Count : 0;
                Session["Notifications"] = notifications.Any() ? notifications : new List<Notification>();

                return Json(new { success = "true" });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in DeleteTruck for truckId: {0} \n\r : {1} - {2}", truckId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetTrucksForDropDown()
        {
            try
            {
                return Json(new { trucksForDropDown = _dataAccessLayer.GetTrucksForDropDown(), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetTrucksForDropDown \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
    }
}

WebProject/Controllers/UsersController.cs
using DataLayer.PersistanceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.App_Start;
using WebProject.Helpers;

namespace WebProject.Controllers
{
    public class UsersController : Controller
    {
        DataAccessLayer.DataAccessLayer _dataAccessLayer = new DataAccessLayer.DataAccessLayer();
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ErrorHelper _errorHelper = new ErrorHelper();
        [Authorization]
        public ActionResult Index()
        {
            return View();
        }
        [Authorization]
        public ActionResult EditUser()
        {
            return View();
        }
        [Authorization]
        public ActionResult GetUsers()
        {
            try
            {
                return Json(new { users = _dataAccessLayer.GetUsers(), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetUsers \n\r : {0}", ex.Message));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetUser(Guid userId)
        {
            try
            {
                return Json(new { user = _dataAccessLayer.GetUser(userId), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetUser with id {0} \n\r : {1} - {2}",userId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult SaveUser(User user)
        {
            try
            {
                var userId = _dataAccessLayer.SaveUser(user);
                return Json(new { userId });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in SaveUser with id {0} \n\r : {1} - {2}", user.Id, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult DeleteUser(Guid userId)
        {
            try
            {
                _dataAccessLayer.DeleteUser(userId);
                return Json(new { success = "true" });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in DeleteUser with id {0} \n\r : {1} - {2}", userId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
    }
}

WebProject/Views/Shared/_Layout.cshtml
@using DataLayer.PersistanceLayer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    @Scripts.Render("~/bundles/jsGrid")
    @Styles.Render("~/Content/cssGrid")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>
<body class="zero-space-body">
    <div class="container-fluid">
        <div class="row no-margin-right">
            @if ((HttpContext.Current.Session["UserId"] != null))
            {
                <div class="col-md-2 left-sidebar">
                    <ul id="sidebar">
                        <li class="black-border" style="font-weight:bold;"><a style="text-decoration:none;color:#ffdc78">@Session["UserFullName"]</a></li>
                        <li class="black-border"><span class="glyphicon glyphicon-road icon-right-position"></span>@Html.ActionLink("Curse", "Index", "Drive", null, new { @class = "menu-item-clickable-aria" })</li>
                        <li class="black-border"><span class="fa fa-truck icon-right-position"></span>@Html.ActionLink("Camioane", "Index", "Truck", null, new { @class = "menu-item-clickable-aria" })</li>
                        <li class="black-border"><span class="far fa-address-card icon-right-position"></span>@Html.ActionLink("Soferi", "Index", "Worker", null, new { @class = "menu-item-clickable-aria" })</li>
                        <li class="black-border"><span class="fas fa-user-plus icon-right-position"></span>@Html.ActionLink("Utilizatori", "Index", "Users", null, new { @class = "menu-item-clickable-aria" })</li>
                        <li class="black-border"><span class="fas fa-car icon-right-position"></span>@Html.ActionLink("Alimentari si Consum", "Index", "Fuel", null, new { @class = "menu-item-clickable-aria" })</li>
                        <li class="black-border" data-toggle="modal" data-target="#notificationsModal"><i id="bellIcon" class="bell-icon far fa-bell icon-right-position icon-black badge"> </i><a href="#" class="menu-item-clickable-aria">Notificari</a></li>
                    </ul>
                </div>
            }
            <div class="@(HttpContext.Current.Session["UserId"] != null ? "col-md-10" : "co-md-12")">
                <div id="errorDialog" title="Error"></div>
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="modal fade" id="notificationsModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content modal-custom">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Notificari</h4>
                </div>
                <div class="modal-body">
                    @if (HttpContext.Current.Session["UserId"] != null)
                    {
                        if (((List<Notification>)Session["Notifications"]).Count > 0)
                        {
                            if (((List<Notification>)Session["Notifications"]).Where(x => x.NotificationType == 0).ToList().Count > 0)
                            {
                                <h5>Acte care urmeaza sa expire</h5>
                                <div class="notification-list">
                                @foreach (var notification in ((List<Notification>)Session["Notifications"]).Where(x => x.NotificationType == 0))
                                {
                                    <div class="alert alert-warning notification-padding" role="alert"><a href="@notification.NotificationLink">@notification.NotificationText</a></div>
                                }
                                </div><br/>
                            }
                            if (((List<Notification>)Session["Notifications"]).Where(x => x.NotificationType == 1).ToList().Count > 0)
                            {
                                <h5>Acte expirate</h5>
                                <div class="notification-list">
                                @foreach (var notification in ((List<Notification>)Session["Notifications"]).Where(x => x.NotificationType == 1))
                                {
                                    <div class="alert alert-danger notification-padding" role="alert"><a href="@notification.NotificationLink">@notification.NotificationText</a></div>
                                }
                                </div>
                            }
                        }
                        else {
                            <h5>Nu exista notificari noi!</h5>
                        }
                        <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Inchide</button>
                    </div>
                    }
                </div>
            </div>
        </div>
        </div>
        @RenderSection("scripts", required: false)
        <script type="text/javascript">
        $("#errorDialog").dialog({
            autoOpen: false,
            maxHeight: 500,
        }).prev(".ui-dialog-titlebar").css("background", "red");

        var str = @Session["NotificationNumber"];
        document.styleSheets[0].addRule('i.badge:after', 'content: "' + str + '";');
        </script>
</body>
</html>