WebProject/Controllers/DriveController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using DataAccessLayer;
using DataLayer.PersistanceLayer;
using WebProject.App_Start;
using WebProject.Helpers;

namespace WebProject.Controllers
{
    public class DriveController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public IDataAccessLayer _dataAccessLayer = new DataAccessLayer.DataAccessLayer();
        public ErrorHelper _errorHelper = new ErrorHelper();
        // GET: Drive
        [Authorization]
        public ActionResult Index()
        {
            ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
            return View();
        }
        [Authorization]
        public ActionResult EditDrive()
        {
            ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
            ViewBag.TrucksForDropDown = _dataAccessLayer.GetTrucksForDropDown();
            ViewBag.DriveStatusesForDropDown = _dataAccessLayer.GetDriveStatuses();
            ViewBag.DriveTypesForDropDown = _dataAccessLayer.GetDriveTypes();
            return View();
        }
        [Authorization]
        public ActionResult GetDrives(string pageIndex, string pageSize, FilterDrivesModel filters)
        {
            try
            {
                var drives = _dataAccessLayer.GetDrives(Convert.ToInt32(pageSize), Convert.ToInt32(pageIndex) - 1, filters);
                var groupings = drives.GroupBy(x => x.Vlaplan).Select(g=> new { Vlaplan = g.Key, Drives = g.ToList(), TotalRows = g.FirstOrDefault().TotalRows }).ToList();

                return Json(new { drives = groupings, JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetDrives \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new
                {
                    error = _errorHelper.GetErrorMessage(ex)
                });
            }
        }
        [Authorization]
        public ActionResult SaveDrive(Drive drive)
        {
            try
            {
                drive.LastUpdateByUser = Guid.Parse(Session["UserId"].ToString());
                return Json(new { driveId = _dataAccessLayer.SaveDrive(drive) });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in SaveDrives with id {0} \n\r : {1} - {2}", drive.Id, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetDrive(Guid idDrive)
        {
            try
            {
                return Json(new { drive = _dataAccessLayer.GetDrive(idDrive), JsonRequestBehavior.AllowGet });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetDrive for drive with id = {0} \n\r : {1} - {2}",idDrive, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult DeleteDrive(Guid driveId)
        {
            try
            {
                _dataAccessLayer.DeleteDrive(driveId);
                return Json(new { success = "true" });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in DeleteDrive for drive with id = {0} \n\r : {1} - {2}", driveId, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult VerifyIfVlarefIsAlreadyUsed(string vlaref)
        {
            try
            {
                var vlarefExists = _dataAccessLayer.VerifyIfVlarefIsAlreadyUsed(vlaref);
                return Json(new { vlarefExists });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in VerifyIfVlarefIsAlreadyUsed for vlaref with id = {0} \n\r : {1} - {2}", vlaref, ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult ExportToExcel()
        {
            try
            {
                log.Info(string.Format("Utilizatorul {0} a descarcat un excel cu toate cursele inregistrate.", Session["Username"]));
                var gv = AdaptGridViewForExport(_dataAccessLayer.GetDrives(99999, 0, new FilterDrivesModel()));

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename=Curse.xls");
                Response.ContentType = "application/ms-excel";
                Response.Charset = "";
                StringWriter objStringWriter = new StringWriter();
                HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                gv.RenderControl(objHtmlTextWriter);
                Response.Output.Write(objStringWriter.ToString());
                Response.Flush();
                Response.End();

                ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
                return View("Index");
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in DriveController - ExportToExcel \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }
        [Authorization]
        public ActionResult GetDrivesForWorkerByDateInterval(Guid workerId, DateTime startDate, DateTime endDate)
        {
            try
            {
                log.Info(string.Format("Utilizatorul {0} a descarcat un excel cu curse pentru soferul {1} in intervalul orar {2} - {3}.", Session["Username"],workerId,startDate,endDate));

                var worker = _dataAccessLayer.GetWorker(workerId);
                var fileName = string.Format("Curse-{0}.xls", worker.WorkerName);

                var gv = AdaptGridViewForExport(_dataAccessLayer.GetDrivesForWorkerByDateInterval(workerId, startDate,endDate));

                Response.ClearContent();
                Response.Buffer = true;
                Response.AddHeader("content-disposition", "attachment; filename="+fileName);
                Response.ContentType = "application/ms-excel";
                Response.Charset = "";
                StringWriter objStringWriter = new StringWriter();
                HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);
                gv.RenderControl(objHtmlTextWriter);
                Response.Output.Write(objStringWriter.ToString());
                Response.Flush();
                Response.End();

                ViewBag.WorkersForDropDown = _dataAccessLayer.GetWorkersForDropDown();
                return View("Index");
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in GetDrivesForWorkerByDateInterval \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new
                {
                    error = _errorHelper.GetErrorMessage(ex)
                });
            }
        }

        private GridView AdaptGridViewForExport(List<Drive> drivesToBeExported)
        {
            var gv = new GridView();
            gv.DataSource = drivesToBeExported;
            gv.DataBind();
            if (drivesToBeExported.Any())
            {
                gv.HeaderRow.Cells[0].Visible = false;
                gv.HeaderRow.Cells[1].Visible = false;
                gv.HeaderRow.Cells[2].Visible = false;
                gv.HeaderRow.Cells[3].Visible = false;
                gv.HeaderRow.Cells[12].Visible = false;
                gv.HeaderRow.Cells[14].Visible = false;
                gv.HeaderRow.Cells[16].Visible = false;
                gv.HeaderRow.Cells[18].Visible = false;
                gv.HeaderRow.Cells[20].Visible = false;
                gv.HeaderRow.Cells[22].Visible = false;
                gv.HeaderRow.Cells[25].Visible = false;
                gv.HeaderRow.Cells[27].Visible = false;
                gv.HeaderRow.Cells[29].Visible = false;
                gv.HeaderRow.Cells[32].Visible = false;
                gv.HeaderRow.Cells[34].Visible = false;
                gv.HeaderRow.Cells[36].Visible = false;
                gv.HeaderRow.Cells[38].Visible = false;
                gv.HeaderRow.Cells[40].Visible = false;
                gv.HeaderRow.Cells[42].Visible = false;
                gv.HeaderRow.Cells[43].Visible = false;
                gv.HeaderRow.Cells[44].Visible = false;
                gv.HeaderRow.Cells[45].Visible = false;
                gv.HeaderRow.Cells[46].Visible = false;
                gv.HeaderRow.Cells[48].Visible = false;
                gv.HeaderRow.Cells[51].Visible = false;
                gv.HeaderRow.Cells[52].Visible = false;
                gv.HeaderRow.Cells[4].Text = Resources.Labels.Sofer;
                gv.HeaderRow.Cells[5].Text = Resources.Labels.NumarInmatriculare;
                gv.HeaderRow.Cells[6].Text = Resources.Labels.Data;
                gv.HeaderRow.Cells[7].Text = Resources.Labels.Vlaplan;
                gv.HeaderRow.Cells[8].Text = Resources.Labels.Vlarref;

WebProject/Controllers/LoginController.cs
using DataLayer.PersistanceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.Helpers;

namespace WebProject.Controllers
{
    public class LoginController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        DataAccessLayer.DataAccessLayer _dataAccessLayer = new DataAccessLayer.DataAccessLayer();
        public ErrorHelper _errorHelper = new ErrorHelper();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(User user)
        {
            try
            {
                var correctUser = _dataAccessLayer.Login(user);
                if (correctUser != null)
                {
                    Session["UserId"] = correctUser.Id.ToString();
                    Session["Username"] = correctUser.Username;
                    Session["UserFullName"] = correctUser.FullName;
                    Session["HasAdminRole"] = correctUser.HasAdminRole;

                    log.Info(string.Format("The user: {0} started a new session", Session["Username"]));

                    var notifications = _dataAccessLayer.GetNotifications();
                    Session["NotificationNumber"] = notifications.Any() ? notifications.Count : 0;
                    Session["Notifications"] = notifications.Any() ? notifications: new List<Notification>();
                }
                return Json(new { userName = correctUser != null ? correctUser.Username : string.Empty });
            }
            catch (Exception ex)
            {
                log.Error(string.Format("Error in Login \n\r : {0} - {1}", ex.Message, ex.StackTrace));
                Response.StatusCode = 500;
                return Json(new { error = _errorHelper.GetErrorMessage(ex) });
            }
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            Session.Abandon();
            return View("~/Views/Login/Index.cshtml");
        }
    }
}

WebProject/Views/Drive/Index.cshtml
@{
    ViewBag.Title = "Curse";
}

<nav class="navbar navbar-inverse nav-bar">
    <div class="container-fluid">
        <div class="navbar-header" style="margin-top: 5px;">
            <a class="navbar-brand nav-bar-text" href="#">@ViewBag.Title</a>
        </div>
        <div class="button-group right-side" style="margin-top: 5px;">
            <div class="btn-group">
                <button class="btn btn-success" id="addDriveButton" onclick="driveController.addNewDrive();"><span class="glyphicon glyphicon glyphicon-plus"></span> @Resources.Labels.Adauga</button>
                <button class="btn btn-success" id="editDriveButton" disabled onclick="driveController.editDrive();"><span class="glyphicon glyphicon glyphicon-edit"></span> @Resources.Labels.Editeaza</button>
                <button class="btn btn-danger" id="deleteDriveButton" disabled onclick="driveController.deleteDrive();"><span class="glyphicon glyphicon glyphicon-remove"></span> @Resources.Labels.Sterge</button>
            </div>
            @Html.ActionLink("Logout", "Logout", "Login", null, new { @class = "no-text-decoration btn btn-primary glyphicon glyphicon-log-out" })
        </div>
    </div>
</nav>
<div class="row">
    <div class="col-md-6">
        <div class="button-group">
            <div class="btn-group" style="display:inline-flex;padding-bottom:7px;">
                @using (Html.BeginForm("ExportToExcel", "Drive", FormMethod.Post))
                {
                    <button class="btn btn-default" id="exportToExcel" type="submit"><i class="fas fa-file-excel"></i> @Resources.Labels.ExportAll</button>
                }
                <button class="btn btn-default" data-toggle="modal" data-target="#exportWorkerToExcelModal" id="exportWorker" type="submit"><i class="fas fa-file-excel"></i> @Resources.Labels.ExportWorker</button>
            </div>
        </div>
    </div>
    @*<div class="col-md-6">
        <div class="input-group" style="padding-top:7px;">
            <input type="text" id="searchText" class="form-control my-search" placeholder="Cauta curse..." style="float:right">
            <span class="input-group-btn">
                <button class="btn btn-primary" onclick="driveController.initGrid();" type="button"><span><i class="glyphicon glyphicon-search"></i></span></button>
            </span>
        </div>
    </div>*@
</div>
<div class="row filter-padding">
    <div class="col-md-2">
        <input type="text" id="filterDriver" onkeypress="driveController.enterPressed(event)" placeholder="@Resources.Labels.Sofer" class="form-control" />
    </div>
    <div class="col-md-2">
        <input type="text" id="filterTruck" onkeypress="driveController.enterPressed(event)" placeholder="@Resources.Labels.Camion" class="form-control" />
    </div>
    <div class="col-md-2">
        <input type="text" id="filterTrail" onkeypress="driveController.enterPressed(event)" placeholder="Remorca" class="form-control" />
    </div>
    <div class="col-md-2">
        <input type="text" id="filterVlaplan" onkeypress="driveController.enterPressed(event)" placeholder="@Resources.Labels.Vlaplan" class="form-control" />
    </div>
    <div class="col-md-2">
        <input type="text" id="filterVlarref" onkeypress="driveController.enterPressed(event)" placeholder="@Resources.Labels.Vlarref" class="form-control" />
    </div>
    <div class="col-md-2">
        <button class="btn btn-primary" id="bntFilter" onclick="driveController.initGrid();" type="button">Filtrare <span><i class="glyphicon glyphicon-filter"></i></span></button>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="driveGrid"></div>
    </div>
</div>
<div class="modal fade" id="exportWorkerToExcelModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content modal-custom">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Resources.Labels.ExportWorkerSettings</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("GetDrivesForWorkerByDateInterval", "Drive", FormMethod.Post))
                {
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="col-md-6">
                                <label>@Resources.Labels.Sofer</label>
                            </div>
                            <div class="col-md-6">
                                <select class="form-control" placeholder="@Resources.Labels.Sofer" id="worker" name="workerId" required>
                                    <option selected disabled hidden style='display: none' value=''></option>
                                    @foreach (var worker in ViewBag.WorkersForDropDown)
                                    {
                                        <option value="@worker.Id" id="@worker.Id" truck-id="@worker.Truck">@worker.WorkerName</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="col-md-6">
                                <label>@Resources.Labels.StartDate</label>
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" autocomplete="off" placeholder="dd/MM/yyyy" id="startDate" name="startDate" type="text" required />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="col-md-6">
                                <label>@Resources.Labels.EndDate</label>
                            </div>
                            <div class="col-md-6">
                                <input class="form-control" autocomplete="off" placeholder="dd/MM/yyyy" id="endDate" name="endDate" type="text" required />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <div class="col-md-6">
                                <button class="btn btn-primary" id="exportWorkerToExcel"><i class="fas fa-file-excel"></i> @Resources.Labels.GenerateExcel</button>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                }
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@Resources.Labels.Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="loadingAnimation" class="row" style="padding-left:40%;margin-top:-25%;position:absolute;">
    <div class="loader"></div>
</div>

<input id="driveId" class="hidden" type="text" />
<script src="~/Scripts/Pages/driveController.js"></script>